import Head from "next/head";
import TitleWithDescription from "../components/title-with-description";
import SpotifyCurrentlyPlaying from "../components/spotify-currently-playing";
import SocialSharePreview from "../components/social-share-preview";

const SpotifyPage = () => {
  const title = "Abdou Ouahib | Spotify";
  const description = "Welcome to my lounge, here you can find the current track" +
    " I'm listening to, and also various playlists, either generated by me, or " +
    "by Spotify algorithms, enjoy!";
  return (
    <div className="flex flex-col max-w-screen-md">
      <Head>
        <title>{title}</title>
        <meta name="description" content={description}/>
      </Head>
      <SocialSharePreview
        image="/static/images/social-share-preview/spotify.png"
        title={title}
        description={description}
      />
      <TitleWithDescription title="Spotify" description={description}/>
      <SpotifyCurrentlyPlaying/>
      <p className="text-center mt-24 text-gray-500 dark:text-gray-400">
        Playlists coming soon...
      </p>
    </div>
  );
};

export default SpotifyPage;