import Head from "next/head";
import TitleWithDescription from "../components/title-with-description";
import SpotifyCurrentlyPlaying from "../components/spotify-currently-playing";

const SpotifyPage = () => {
  const title = "Abdou Ouahib | Spotify";
  const description = "Welcome to my lounge, here you can find the current track" +
    " I'm listening to, and also various playlists, either generated by me, or " +
    "by Spotify algorithms, enjoy!";
  return (
    <div className="max-w-screen-md">
      <Head>
        <title>{title}</title>
        <meta name="description" content={description}/>
      </Head>
      <TitleWithDescription title="Spotify" description={description}/>
      <SpotifyCurrentlyPlaying/>
    </div>
  );
};

export default SpotifyPage;