# This is an action that calls an API endpoint every ${duration}
# Calling that endpoint updates my Spotify playlist

name: UpdateLikedSongs

# Controls when the action will run. 
on:
  # Schedules the cron job to be run every ${duration}
  schedule:
    - cron: "5 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This workflow has one job
jobs:
  # The cron job
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call the API endpoint
        run: |
          curl --request POST \
          --url 'https://abdou.dev/api/spotify/update-liked-songs' \
          --header 'secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}'
