# This is an action that calls an API endpoint regularly
# Calling that endpoint updates my Spotify playlist

name: UpdateLikedSongs

# Controls when the action will run.
on:
  # Schedules the cron job to be run every 5 minutes (theoretically, but in
  # practice, it's every hour or so)
  schedule:
    - cron: "0 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This workflow has one job
jobs:
  # The cron job
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the action
        uses: actions/checkout@v2
        with:
          repository: aouahib/spotify-job
          token: ${{ secrets.GH_PAT }}
          ref: main
      - name: Execute the action
        uses: ./
        with:
          secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
